branches:
  only:
  - master
  - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
language: go
go: 1.14.x
os:
- osx
- linux
cache:
- directories:
  - "$GOPATH/bin"
  - "$GOPATH/pkg"
  - "$PWD/tmp"
script:
- make bootstrap
- make lint
- make test
jobs:
  include:
  - stage: docs
    name: "JSON to Schema"
    before_install:
    - sudo apt-get install -y python3 python3-pip python3-setuptools
    - sudo pip3 install --upgrade pip
    - sudo pip3 install virtualenv
    - virtualenv env
    - source env/bin/activate
    language: go
    os: linux
    go: 1.14.x
    script:
    - make gen_schema
    - make doc
    deploy:
      token:
        secure: YLKnp2qbiI9vY++j0JMePZDhGBVVZNg7fqCrPXQ3PZAIR5fGFR6XBTSDR4i20ZJYJVgTIQFADyqtuGk5kL9oF2hvYVCxpc5/IvBz135JGB5ZW19jQcBfkMPuJ8vdAOvmAoTYhcNjskDGLWcPSDvShvZ5c2K0JbJmQr+Wbr7mAnk0N+L86yAuTqvhksXNHo7PWRQs2xxk89tcMFtzNTNKIKko4pZneuIjcjDfgdfuz+fnU54CZX7OQHgs75jMYmLMZa++ljBJbnxnkXRE4TECmQKVAfDCfttrqzOSmKBqsRxbmFQlBT3zYdpXLENsXewrXkYOtHlPluXhiA7iR8WWuVCOsxg1bCJa5xIEPzsgn4s3Gq7PzXChYcuitetSivj8DSIlJJNsTV//H6LrvzPBCcAGJLDf6nssJQWwlMyHVjEh9rop/ZhYzC23IM4l9RNZ0juZcgtX04RpmcKmm2plEdB/3QGeiOG84pH7U773f6g8EzlQ/veQn/Mw4y+vbGon8j9m4fedKs4r7gTtKed4OZCPKrtkAqyKmo5EWdsZn/Bep6NnnjawIREiZNioYc8YovrjpLZqWA9X7OhfC1HG1fXrRTMpl71VySR99FuoexVaZjrOpZc2lLbrz3+rtVUp+GvQOS1tTYiAtangN2RkBlijHLiVpt3YfQ2zWrooDx4=
      provider: pages
      cleanup: false
      edge: true
      strategy: git
      keep_history: true
      on:
        branch: master
